services:
  - type: web
    name: car-advisor-app
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production